### ISSUE TITLE
Distance to load grass in meters

### ISSUE THREAD

**Issue by javidevalc** [Fobri/Terraxel-Unity#2]
I like so much your job! i am trying to learn and use some tool to generate chunks with infinite terrain, but its not easy at all. 

Can I ask you if there would be a way to control the grass biome loading according to the distance in meters? I would love to be able to load the grass from when it loads the next chunk even if it is far away. 

I would also like to know how to load another biome other than green land.

If you launch a product for the asset store I would be happy to buy it.

Best Regards!

**Comment by Fobri** [comment]
Hi
I couldnt figure out the grass in any smart way. Thats partially why I stopped working on this, because I couldn't find a way to generate the grass and control the distance easily.
I was originally planning to add biomes as well, maybe I will revisit the project some time and add it.
